### ISSUE TITLE
jd_task_global.js 签到: undefined

### ISSUE THREAD

**Issue by xiamo008** [qitoqito/kedaya#103]
![image](https://github.com/user-attachments/assets/d05670fc-746d-4763-aa0d-95105f3ce713)
有自建sign
![image](https://github.com/user-attachments/assets/0b94fbea-d659-445c-9e72-9d5dae60836b)

**Comment by qitoqito** [comment]
sign服务能否正常访问
也有可能黑ip

**Comment by xiamo008** [comment]
> sign服务能否正常访问 也有可能被黑

![image](https://github.com/user-attachments/assets/8fbfde4e-c4dd-4acd-bc40-ef6b291173d9)
sign 应该是没问题的，ip加了巨量的IP。还是这个，放弃抵抗了。难搞
