### ISSUE TITLE
大佬，818手机节不运行是什么问题啊？

### ISSUE THREAD

**Issue by depo0097** [qitoqito/kedaya#107]
大佬，818手机节不运行是什么问题啊？![Screenshot_2024-08-10-13-42-06-573_smartsolutions.adblocker.browser.jpg](https://github.com/user-attachments/assets/bb860c60-5352-4c51-995c-4366cf21292f)

**Comment by qitoqito** [comment]
没安装 node-file-cache模块

**Comment by depo0097** [comment]
要怎么做啊？大佬。 这样对吗![Screenshot_2024-08-10-15-36-29-931_smartsolutions.adblocker.browser.jpg](https://github.com/user-attachments/assets/4ffba009-ac00-4f46-a462-21b113a55d6b)

**Comment by depo0097** [comment]
大佬，方便加一下tg或者是微信吗？
