### ISSUE TITLE
已安装依赖，还是Cannot find module 'fileCache'

### ISSUE THREAD

**Issue by xiamo008** [qitoqito/kedaya#108]
![image](https://github.com/user-attachments/assets/5ea15c8f-8c91-4e8b-90ea-decc77f48528)
![image](https://github.com/user-attachments/assets/a61e82e3-82e9-4fd5-a0ef-1171eb416f9e)

**Comment by qitoqito** [comment]
没安装 
这个要搜索名称进行安装
建议你去bug龙那边了解面板操作
