### ISSUE TITLE
你好麻烦问下你所使用的青龙版本

### ISSUE THREAD

**Issue by knowledgeablelmh** [qitoqito/kedaya#12]
2.12.2在使用时，可以拉库但是添加不了任务，

**Comment by knowledgeablelmh** [comment]
分开输入还能定时拉库吗？

**Comment by qitoqito** [comment]
不用面板
看下有没有用全局代理导致登陆失败

**Comment by knowledgeablelmh** [comment]
rm -rf /ql/repo/qitoqito_kedaya && ql repo https://github.com/qitoqito/kedaya.git kedaya && cp -a /ql/repo/qitoqito_kedaya/. /ql/scripts && task qitoCreat.js now用的这个命令 怎么都不能添加 任务。。。。

**Comment by knowledgeablelmh** [comment]
2.10.13 可以使用 我是说 2.12.的青龙用不了

**Comment by qitoqito** [comment]
> 2.10.13 可以使用 我是说 2.12.的青龙用不了

rm -rf /ql/data/repo/qitoqito_kedaya && ql repo https://github.com/qitoqito/kedaya.git kedaya && cp -a /ql/data/repo/qitoqito_kedaya/. /ql/data/scripts && task qitoCreat.js now

**Comment by knowledgeablelmh** [comment]
原来是这样。。感谢大佬
