### ISSUE TITLE
wdz显示黑号  但是其实正常的  

### ISSUE THREAD

**Issue by beggerlove** [qitoqito/kedaya#14]

**Comment by qitoqito** [comment]
没ck小号,暂时没办法测试

**Comment by beggerlove** [comment]
好的 鸭叔可以入群吗👽想让鸭叔带带

**Comment by beggerlove** [comment]
> 没ck小号,暂时没办法测试

鸭叔  微定制还是不行 增加了类型后  提示我已经领取过奖励了 但是我刚开始跑  手动进去一次也还是不行  今天的直接告诉我没有获取到进度条  ![Screenshot_2022-06-14-16-37-19-90_87c2225eebc34d2513fa0e7ad5b93cfc.jpg](https://user-images.githubusercontent.com/65286493/173533527-7c68da8e-da2c-4917-9d92-f9085a052324.jpg)![Screenshot_2022-06-14-16-37-09-10_948cd9899890cbd5c2798760b2b95377.jpg](https://user-images.githubusercontent.com/65286493/173533556-fc4de2e2-756d-4483-831c-d7fd80dff98f.jpg)鸭叔带带
