### ISSUE TITLE
使用最新版青龙2.12.2收不到推送的消息

### ISSUE THREAD

**Issue by danteswx** [qitoqito/kedaya#15]
是不是因为目录多了一层的缘故？

**Comment by knowledgeablelmh** [comment]
通知写到配置文件里

**Comment by danteswx** [comment]
> 通知写到配置文件里

config.sh写了，没用。

**Comment by qitoqito** [comment]
> > 通知写到配置文件里
> 
> config.sh写了，没用。
将相关通知token放到jd.ini里面试看看
之前也有人有类似问题

**Comment by danteswx** [comment]
解决了，要用库自带的通知字段才可以，用青龙自带的不行。
