### ISSUE TITLE
通知单独用户不生效

### ISSUE THREAD

**Issue by daybreak-git** [qitoqito/kedaya#18]
大佬，我按频道的教程设置，不知为何就不生效。先在环境变量填了custom=IGOT_TOKEN,然后至执行了jd_task_user.js，再去jdUser.js填写IGOT_TOKEN的值，可是就不生效。
是我哪里填写错了吗，没领悟到你的意思

**Comment by qitoqito** [comment]
删除你环境变量加的custom

在jd.ini添加
[jd_task_user]
custom=IGOT_TOKEN

**Comment by daybreak-git** [comment]
搞定了，谢谢！
