### ISSUE TITLE
Win系统电脑nodejs本地怎么运行可达鸭？


### ISSUE THREAD

**Issue by xiamo008** [qitoqito/kedaya#24]
大佬，我在本地下载好了你的整个裤，但是一直不懂那个环境变量是写在那个文件里面啊，求带。

**Comment by qitoqito** [comment]
config里面有个test.ini,重命名jd.ini就行,或者新建

**Comment by shenmadouyaowen** [comment]
> config里面有个test.ini,重命名jd.ini就行,或者新建

大佬,监控可以设置队列形式么

**Comment by xiamo008** [comment]
> config里面有个test.ini,重命名jd.ini就行,或者新建

好的蟹蟹，鸭鸭老板

**Comment by xiamo008** [comment]
![N97@ZG42{S_91ZGX38SH5A4](https://user-images.githubusercontent.com/90441350/177022197-30165ce4-6b4a-4f2e-a758-fb0e7b156034.png)
老板。我填了token了，但是一直还是提示我请正确填写变量。

E:\JDmainx\scripts\parse\jd
通过这个路径倒是不提示了，但是就没得下文，回车后 几秒钟就结束了，麻烦大佬有时间的时候指教下谢谢

**Comment by qitoqito** [comment]
是不是scripts同层目录有config文件夹,里面放了jd.ini?

**Comment by qitoqito** [comment]
> ![N97@ZG42{S_91ZGX38SH5A4](https://user-images.githubusercontent.com/90441350/177022197-30165ce4-6b4a-4f2e-a758-fb0e7b156034.png) 老板。我填了token了，但是一直还是提示我请正确填写变量。
> 
> E:\JDmainx\scripts\parse\jd 通过这个路径倒是不提示了，但是就没得下文，回车后 几秒钟就结束了，麻烦大佬有时间的时候指教下谢谢

是不是scripts同层目录有config文件夹,里面放了jd.ini?
