### ISSUE TITLE
成功运行jd_task_user且显示user写入成功 但找不到生成的jdUser文件

### ISSUE THREAD

**Issue by Heart-Ace** [qitoqito/kedaya#26]
![20220703201847](https://user-images.githubusercontent.com/28911837/177039590-f154af5c-290e-442b-b97e-fab4e9b464a8.jpg)

在scripts/config中并没有生成jdUser文件 同时也找了config目录下同样没有

**Comment by qitoqito** [comment]
如果其他脚本通知有显示 账号n : pin
就有写入

**Comment by Heart-Ace** [comment]
![屏幕截图 2022-07-04 083040](https://user-images.githubusercontent.com/28911837/177063035-0a680916-a8f7-4ae6-8862-115d43c343a8.png)

其他脚本确实也是有显示 账号的
