### ISSUE TITLE
青龙新版本目录变更，无法拉取

### ISSUE THREAD

**Issue by ZERQREZ** [qitoqito/kedaya#28]
由/ql/scripts变为/ql/data/sctipts
所有数据变为data分区内

**Comment by qitoqito** [comment]
rm -rf /ql/data/repo/qitoqito_kedaya && ql repo https://github.com/qitoqito/kedaya.git kedaya && cp -a /ql/data/repo/qitoqito_kedaya/. /ql/data/scripts && task qitoCreat.js now
