### ISSUE TITLE
wuxian非法


### ISSUE THREAD

**Issue by xiamo008** [qitoqito/kedaya#30]
https://lzkj-isv.isvjcloud.com/wxCollectionActivity/activity2/f0316f0443184495a67ea0fc850f187c?activityId=f0316f0443184495a67ea0fc850f187c
![IMG_20220714_190558.jpg](https://user-images.githubusercontent.com/90441350/178969079-990ddb0c-8711-44fc-9d9d-a30ba9d59d12.jpg)
鸭老板抽空看下呢，辛苦啦

**Comment by qitoqito** [comment]
id问题 自己看下通过url能不能正常获取到京豆
