### ISSUE TITLE
大牌集合任务助力

### ISSUE THREAD

**Issue by xiamo008** [qitoqito/kedaya#31]
![1658283606(1)](https://user-images.githubusercontent.com/90441350/179882013-e9f640d6-3c1e-4893-8ee1-a764734e02bb.jpg)
![1658283166(1)](https://user-images.githubusercontent.com/90441350/179882014-10dcda90-2043-46dc-b74f-20d728ff786c.jpg)

鸭老板，你看下大牌集合任务变量是这么写不呢，我主要是想请教下助力，我的hep=写的是我的pin，但是任务结束了也没有助力。是我没写对，还是暂时大牌集合不支持助力任务呢
这次的大牌是 custom=1f0a47f709f74784a_220720
谢谢~

**Comment by qitoqito** [comment]
脚本没开卡助力

**Comment by xiamo008** [comment]
> 脚本没开卡助力

好的，谢谢
