### ISSUE TITLE
redis测试链接是否有通知？

### ISSUE THREAD

**Issue by knowledgeablelmh** [qitoqito/kedaya#33]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/83534987/184689729-52d9bd30-bc1a-40f7-95dd-e54f086f4e80.png">
这样是成功链接了吗？

**Comment by qitoqito** [comment]
> <img alt="image" width="506" src="https://user-images.githubusercontent.com/83534987/184689729-52d9bd30-bc1a-40f7-95dd-e54f086f4e80.png">
> 这样是成功链接了吗？

不对 如果是本机局域网 host填写局域网ip 如果是vps 填写外网ip

**Comment by Jejz168** [comment]
能不能支持redis4.0写法

**Comment by qitoqito** [comment]
> 能不能支持redis4.0写法

redisCli节点内 添加
version=4.0

**Comment by knowledgeablelmh** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/83534987/184805443-b5b85463-0bdb-4737-b0d6-59329a13c7e2.png">
好了
