### ISSUE TITLE
作者您好，我目前使用农场1对1通知，维护了nickName。脚本里提示了昵称替换成功，但是统治里没有替换

### ISSUE THREAD

**Issue by xinhunshang** [qitoqito/kedaya#4]

**Comment by xinhunshang** [comment]
正在向账号18: XXXX 单独推送通知
push+发送一对一通知消息完成🎉（这里的没有替换）

**Comment by qitoqito** [comment]
如果有设置nickName
整体推送会显示nickName,方便管理者管理维护
单独通知 设定成显示用户名/pin
如果是挂几个号的用户,方便用户知道是哪个账号活动完成
同时也避免因管理员添加的nickNane给用户造成歧义,不知道哪个具体账号
