### ISSUE TITLE
无线组队问题

### ISSUE THREAD

**Issue by xiamo008** [qitoqito/kedaya#43]
鸭鸭老板，我现在用的是win版的docker，10分钟换一次ip，就是有个问题，无线在跑cj或者其他组队任务时，在助力前面2个ck之后，第三个ck开始助力 就会提示“可能是黑号或者黑ip,停止运行”，我ppoe重新拨号后 或者停止10分钟以后重新跑 还是可以运行。
我想请教下，可不可以给无线类的脚本增加一个 延时和使用IP代理（例如星空代理 http://www.xkdaili.com/ 之类的）的变量，在脚本提示黑号时候自动使用代理IP 切换IP地址，从而实现继续完成任务的功能呀，其次就是在助力过ck1的CK 就不要在重复去助力ck2。减少重复循环逻辑，降低黑号的风险。

在您有空的时候可以帮忙解答下，谢谢。![Screenshot_20220923_223909.jpg](https://user-images.githubusercontent.com/90441350/191989088-24d335a4-9e08-48fb-b716-dba9a3c2a739.jpg)

**Comment by qitoqito** [comment]
代理只支持http/socks
至于你说的助力情况,可以添加脚本节点 
model=help
试用于账号只有一次助力机会的情况,前n个号助力完A,从n+1个号开始助力B

**Comment by xiamo008** [comment]
> 代理只支持http/socks
> 至于你说的助力情况,可以添加脚本节点 
> model=help
> 试用于账号只有一次助力机会的情况,前n个号助力完A,从n+1个号开始助力B

嗯嗯，我现在用了你发的这个，model=help后，助力循环已经解决了。
代理的话，星空也有socks5的代理链接，我发图你看下，这样的可不可以用，谢谢。[Screenshot_20220924_115034_edit_414623844690900.jpg](https://user-images.githubusercontent.com/90441350/192078867-e1cb1409-9591-4a35-98c5-b42e4bb17756.jpg)。
