### ISSUE TITLE
jd_task_shopappSign.js京东左侧店铺抽奖

### ISSUE THREAD

**Issue by heimawsw** [qitoqito/kedaya#54]
京东左侧店铺抽奖
## 执行结束... 2022-11-29 18:03:40  耗时 3 秒

我是青龙，单拿出来了这个js跑，配置了 
export QITOQITO_PLATFORM
export filename_expand
两个环境变量，运行脚本后，日志是上面开始和结束就没了，中间是空的，也没有报错。这是什么问题。。

**Comment by qitoqito** [comment]
有先qitoCreat运行生成入口文件再跑?
