### ISSUE TITLE
任务异常

### ISSUE THREAD

**Issue by sum211** [qitoqito/kedaya#58]
![Screenshot_20221215-144238](https://user-images.githubusercontent.com/68324538/207791222-40665eb2-dd4b-49e6-bf73-81680dbd1c8f.jpg)

--------
TypeError this[_0x3809e8[_0x359c9d.UuOOQ]] is not a function

**Comment by sum211** [comment]
所有的都是这个样子

**Comment by qitoqito** [comment]
看下环境变量有没有getUa字段
或者没有完全更新库文件

**Comment by sum211** [comment]
环境变量没有
重新拉了，两个命令都试了一下，没有改变
