### ISSUE TITLE
拉库有文件，但是定时任务添加失败

### ISSUE THREAD

**Issue by qa2286805252** [qitoqito/kedaya#65]
报错代码如下
TypeError: Cannot read properties of undefined (reading 'code')
    at /ql/scripts/qitoCreat.js:186:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by qa2286805252** [comment]
手动添加任务可以执行

**Comment by qa2286805252** [comment]
青龙是用手机装的

**Comment by chlchl1** [comment]
你解决了吗
