### ISSUE TITLE
util/jdAlgo.js更新后jd_task_inviteFission.js助力几个直接错误

### ISSUE THREAD

**Issue by mrright-cyber** [qitoqito/kedaya#79]
大佬好，自从更新到最新的 util/jdAlgo.js 后，助力 6 个 ck 后一直显示【助力错误】

麻烦大佬过目下，辛苦鸭叔。

![image](https://github.com/qitoqito/kedaya/assets/61380864/cdc32c57-34ad-4fb4-b5c6-02491d9452b9)

**Comment by airdge** [comment]
嗯  H5ST4.4这个版本 对于多账号使用同个ua貌似有限制,运行到第6-7个时候就没数据 
之前H5ST4.2之前的版本 没有这个限制

**Comment by qitoqito** [comment]
更新看下
下午测试了下,如果所有使用同个ua,在第6个左右就开始限制
换成缓存单个账户ua/每请求一个url切换一个ua 则没问题
H5ST4.4这个版本多了ua限制,不让使用同个ua
