### ISSUE TITLE
所有任务执行报错，token超时,请重新获取    请问下是什么原因

### ISSUE THREAD

**Issue by 15991491954** [qitoqito/kedaya#8]
## 开始执行... 2022-04-02 21:34:36

token超时,请重新获取

## 执行结束... 2022-04-02 21:34:37  耗时 1 秒

**Comment by qitoqito** [comment]
https://t.me/qitoqito

**Comment by char1eslu** [comment]
> https://t.me/qitoqito

抱歉打扰了，请问Turning Lab 的群是解散了吗还是怎么了，我今天突然发现群不见了，是清了长时间不说话的人吗，唉，也没有收到通知什么的

**Comment by xiaoyi0106** [comment]
> 

ID是多少

**Comment by char1eslu** [comment]
> > > https://t.me/qitoqito
> > 
> > 
> > 问候还是了，请问图灵实验室的群是散了吗，我今天突然发现群不见了，是很长时间不明白的人吗，​​唉，也没有收到通知什么的
> 
> ID多少

@charles_lu
