### ISSUE TITLE
Cannot create property 'undefined' on string ''

### ISSUE THREAD

**Issue by MavonCmc** [qitoqito/kedaya#80]
一跑就报这个错是哪里问题

**Comment by qitoqito** [comment]
可能你本地的环境变量跟脚本冲突

**Comment by MavonCmc** [comment]
全新的环境也报这个错啊，哪些环境变量是必须的？

**Comment by qitoqito** [comment]
win系统?
重新拉库试下

**Comment by MavonCmc** [comment]
解决了，另外sign接口怎么搭建啊？有教程吗？返回结果有要求吗？

**Comment by qitoqito** [comment]
`docker run -dit \
  --name official \
  --restart always \
  --hostname official \
  -p 9527:80 \
  qninq/signapi:latest`

`QITOQITO_JDSIGN=http://ip:port/jd/sign`

**Comment by qitoqito** [comment]
`docker run -dit  --name official  --restart always  --hostname official  -p 9527:80 qninq/signapi:latest`
