### ISSUE TITLE
京东店铺连续签到运行出现问题

### ISSUE THREAD

**Issue by hongwang0000** [qitoqito/kedaya#81]
![捕获](https://github.com/qitoqito/kedaya/assets/76648269/815f6308-d398-44b3-9868-bb676ab41af4)
fileCache.js依赖文件也在util文件夹内，为什么脚本不运行呢？望大佬有空帮看看

**Comment by qitoqito** [comment]
安装node-file-cache

**Comment by hongwang0000** [comment]
谢谢大佬，可以了。零点签到容易火爆，有没有设置重试次数的变量，这样可以多试几次

**Comment by qitoqito** [comment]
filename_turn=n 
filename指具体脚本名

**Comment by hongwang0000** [comment]
好的，谢谢佬
