### ISSUE TITLE
jd_task_shopSign.js  报错了  不知道啥情况

### ISSUE THREAD

**Issue by chlchl1** [qitoqito/kedaya#85]
日志-kedaya_京东店铺连续签到
## 开始执行... 2024-05-03 14:52:35

Cannot find module 'fileCache'
Require stack:
- /ql/scripts/util/common.js
- /ql/scripts/template.js
- /ql/scripts/parse/jd/jd_task_shopSign.js
- /ql/scripts/jd_task_shopSign.js

## 执行结束... 2024-05-03 14:52:35 耗时 0 秒

**Comment by qitoqito** [comment]
npm install node-file-cache

**Comment by chlchl1** [comment]
谢谢大佬&nbsp; &nbsp; 明白了


a&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;怀恋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qitoqito/kedaya"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月6日(星期一) 下午5:33
***@***.***&gt;;
抄送:&nbsp;"a                   ***@***.******@***.***&gt;;
主题:&nbsp;Re: [qitoqito/kedaya] jd_task_shopSign.js  报错了  不知道啥情况 (Issue #85)





 
npm install node-file-cache
