### ISSUE TITLE
jd_task_hudong 是否可以支持 sourceCode=ace454250 和 aceaceqingzhan 类型的活动

### ISSUE THREAD

**Issue by mrright-cyber** [qitoqito/kedaya#86]
3月底新出的活动，活动链接：`https://pro.m.jd.com/mall/active/3mknCJXM9fpJGueqd7BDdknZgFpt/index.html`

通过抓包 `/functionId=queryInteractiveInfo` 接口得到如下参数：

```
appid=home-channel
functionId=queryInteractiveInfo
body={"encryptProjectId":"6pvWvhxzcHzeEiWsqP5oKgUbHEy","sourceCode":"ace454250","rewardEncryptAssignmentId":"2oGxy3iBrKw3YFG2Z7DGWFNXxVkT","assistEncryptAssignmentId":"36a4jWTk5hyZS5fq76FhWKHGHm9a","assistInfoFlag":4,"assistNum":5}}
```

目前测试得到，jd_task_hudong.js 好像仅支持 sourceCode: 'acerwq20220316' 的活动

`sourceCode: 'aceaceqingzhan'` 和 `sourceCode: 'ace454250'` 好像都还没支持

`sourceCode: 'aceaceqingzhan'` 的活动链接：`https://pro.m.jd.com/mall/active/34oVq6LqN9Yshb8Y841RXHG3Nzf7/index.html`

**Comment by chlchl1** [comment]
你好  咨询一下   青龙2.16.X怎么拉库呀
