### ISSUE TITLE
鸭鸭老师 jd_task_shopGift 是否有变量可以设置

### ISSUE THREAD

**Issue by xiamo008** [qitoqito/kedaya#91]
![1716603474302](https://github.com/qitoqito/kedaya/assets/90441350/8219b303-437f-43e2-9bee-3f511abfb996)
鸭鸭老师，我想请教下，这个活动，能否设置 跑多少个ck  都是没有没奖品的情况下，自动停止下呀，不然运行一次就得跑半天一直不停

**Comment by qitoqito** [comment]
没有   跑过的id在下次运行时会跳过

**Comment by xiamo008** [comment]
> 没有跑步id在下次出行跳过

好嘛，谢谢鸭鸭老师了
